"""
URL configuration for littlelemon project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from Restaurant.views import BookingViewSet

# Utility that automatically creates URL routing for viewsets
# DefaultRouter includes root view, while SimpleRouter does not
# All base routes registered under the router
# Root view example:
# {"tables": "http://127.0.0.1:8000/restaurant/booking/tables/"}
# Specifically designed for use with ViewSets
from rest_framework.routers import DefaultRouter

# Initialize the router, to manage the URL patterns
router = DefaultRouter()
# Wire up the tables URL route with the BookingViewSet
router.register(r'tables', BookingViewSet)

urlpatterns = [
   path('admin/', admin.site.urls),
   path('restaurant/', include('Restaurant.urls')),
   # Adds all the routes generated by the router
   path('restaurant/booking/', include(router.urls))
]
